apiVersion: v1
kind: Service
metadata:
  name: node-app-service
spec:
  type: LoadBalancer       # or ClusterIP if internal only
  selector:
    app: node-app
  ports:
    - protocol: TCP
      port: 80             # service port
      targetPort: 8000     # container port
